apiVersion: v1
kind: Pod
metadata:
  name: webserver
  namespace: poc
spec:
  containers:
  - name: webserver
    image: {{ .Values.myapp.app.image.repository }}:{{ .Values.myapp.app.image.tag }}
    ports:
    - containerPort: 80